server:
  port: 8080
  servlet:
    context-path: /bs

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/yellow_car?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    remove-abandoned-timeout: 7200
    default-auto-commit: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.slx.bs.po